# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: chutador_user
  password: A9lxuf1jgZxyp0er5rlOIcg3I3YEnbXq
  host: dpg-cidhq0tph6eoun89a3r0-a
  port: 5432

production: 
  <<: *default
  database: chutador
